
DROP DATABASE IA_APP;


CREATE DATABASE IA_APP;

/*Tabla de menus*/
DROP TABLE IA_APP.T_MENUS;
CREATE TABLE IA_APP.T_MENUS(NOMBRE_MENU VARCHAR(100) NOT NULL,
							OPCION_MENU INT          NOT NULL,
							DESCRIPCION VARCHAR(100) NOT NULL,
							NEXT_MENU   VARCHAR(100) NOT NULL);

ALTER TABLE IA_APP.T_MENUS
	ADD CONSTRAINT PK_T_MENUS PRIMARY KEY(NOMBRE_MENU, OPCION_MENU);

INSERT INTO IA_APP.T_MENUS VALUES('menuPrincipal', 0, 'Salir', 'Salir');

INSERT INTO IA_APP.T_MENUS VALUES('menuPrincipal', 1, 'Acceder a escenario existente', 'escenariosExistentes');

INSERT INTO IA_APP.T_MENUS VALUES('menuPrincipal', 2, 'Crear nuevo escenario', 'escenarioNuevo');

INSERT INTO IA_APP.T_MENUS VALUES('MENU_ESCENARIO', 0, 'Volver', 'escenariosExistentes');

INSERT INTO IA_APP.T_MENUS VALUES('MENU_ESCENARIO', 1, 'Ver parametros', 'verParamEscenario');

INSERT INTO IA_APP.T_MENUS VALUES('MENU_ESCENARIO', 2, 'Modificar parametros', 'modParamEscenario');

INSERT INTO IA_APP.T_MENUS VALUES('MENU_ESCENARIO', 3, 'Procesar ficheros', 'procesaFicheros');

INSERT INTO IA_APP.T_MENUS VALUES('MENU_ESCENARIO', 4, 'Modificar Autocorrelaciones', 'modAutoCorrel');

INSERT INTO IA_APP.T_MENUS VALUES('MENU_ESCENARIO', 5, 'Borrar escenario', 'borraEscenario');

INSERT INTO IA_APP.T_MENUS VALUES('MENU_AUTOCORR', 0, 'Volver', 'escenariosExistentes');



/*Tabla de usuarios*/
DROP TABLE IA_APP.T_USUARIOS;
CREATE TABLE IA_APP.T_USUARIOS(NOMBRE VARCHAR(100),
							   CONTRA VARCHAR(100),
							   EMAIL  VARCHAR(100));

ALTER TABLE IA_APP.T_USUARIOS
	ADD CONSTRAINT PK_T_USUARIOS PRIMARY KEY(NOMBRE);
	
INSERT INTO IA_APP.T_USUARIOS VALUES('jbeneitezh', 'jbeneitezh', 'javier.beneitez.hernandez1989@gmail.com');
INSERT INTO IA_APP.T_USUARIOS VALUES('jb', 'jb', 'javier.beneitez.hernandez1989@gmail.com');

/*Tabla de escenarios*/
DROP TABLE IA_APP.T_ESCENARIOS;
CREATE TABLE IA_APP.T_ESCENARIOS(ID_ESCENARIO   INT          NOT NULL,
								 NOMBRE         VARCHAR(100) NOT NULL,
								 F_CREACION     DATETIME     NOT NULL,
								 F_MODIFICACION DATETIME     NOT NULL,
								 F_OPTIMIZACION DATETIME     NULL);

ALTER TABLE IA_APP.T_ESCENARIOS
	ADD CONSTRAINT PK_T_ESCENARIOS PRIMARY KEY(ID_ESCENARIO);
ALTER TABLE IA_APP.T_ESCENARIOS
	ADD CONSTRAINT UK_T_ESCENARIOS UNIQUE KEY(NOMBRE);

/*tabla de campos de parametrización para cada escenario*/	
DROP TABLE IA_APP.T_CONFIG_ESC_PARAM;
CREATE TABLE IA_APP.T_CONFIG_ESC_PARAM(ID_PARAM      INT          NOT NULL,
									   DESCRIPCION   VARCHAR(100) NOT NULL,
									   DATA_TYPE     VARCHAR(100) NOT NULL,
									   MODIFICABLE   INT);

									   
ALTER TABLE IA_APP.T_CONFIG_ESC_PARAM
	ADD CONSTRAINT PK_T_CONFIG_ESC_PARAM PRIMARY KEY(ID_PARAM);

ALTER TABLE IA_APP.T_CONFIG_ESC_PARAM
	ADD CONSTRAINT UK_T_CONFIG_ESC_PARAM UNIQUE KEY(DESCRIPCION);

CREATE INDEX IND_T_CONFIC_ESC_PARAM ON IA_APP.T_CONFIG_ESC_PARAM(ID_PARAM, MODIFICABLE);

CREATE INDEX IND_T_CONFIC_ESC_PARAM_2 ON IA_APP.T_CONFIG_ESC_PARAM(MODIFICABLE);

CREATE INDEX IND_T_CONFIC_ESC_PARAM_3 ON IA_APP.T_CONFIG_ESC_PARAM(ID_PARAM, MODIFICABLE);
	
INSERT INTO IA_APP.T_CONFIG_ESC_PARAM VALUES(1,   'Nombre_Fic_Data_Input', 'VARCHAR(100)' , 1);
                                                                             
INSERT INTO IA_APP.T_CONFIG_ESC_PARAM VALUES(2,   'Nombre_Fic_Data_Output', 'VARCHAR(100)', 1);
                                                                             
INSERT INTO IA_APP.T_CONFIG_ESC_PARAM VALUES(3,   'Ficheros_Cargados', 'INT', 0);
                                                                             
INSERT INTO IA_APP.T_CONFIG_ESC_PARAM VALUES(4,   'Tipo_Optimizacion', 'INT', 1);
                                                                             
INSERT INTO IA_APP.T_CONFIG_ESC_PARAM VALUES(5,   'Num_Soluciones', 'INT', 1);
                                                                             
INSERT INTO IA_APP.T_CONFIG_ESC_PARAM VALUES(99,  'Vueltas_por_Iteracion', 'INT', 1);

INSERT INTO IA_APP.T_CONFIG_ESC_PARAM VALUES(100, 'Max_Precision_Decimales', 'INT', 1);

INSERT INTO IA_APP.T_CONFIG_ESC_PARAM VALUES(102, 'Max_Cambio', 'NUMERIC(20,18)', 1);



/*Tabla de parametrizaciones posibles para los parametros que sólo pueden tener unos valores determinados*/
DROP   TABLE IA_APP.T_PARAM_VALORES_VALIDOS;

CREATE TABLE IA_APP.T_PARAM_VALORES_VALIDOS(ID_PARAM    INT           NOT NULL,
											ID_OPCION   INT           NOT NULL,
											DESCRIPCION VARCHAR(200)  NOT NULL);

ALTER TABLE IA_APP.T_PARAM_VALORES_VALIDOS
	ADD CONSTRAINT PK_T_PARAM_VALORES_VALIDOS PRIMARY KEY(ID_PARAM, ID_OPCION);	

ALTER TABLE IA_APP.T_PARAM_VALORES_VALIDOS
	ADD CONSTRAINT FK_T_PARAM_VALORES_VALIDOS FOREIGN KEY(ID_PARAM) REFERENCES IA_APP.T_CONFIG_ESC_PARAM(ID_PARAM);		

INSERT INTO IA_APP.T_PARAM_VALORES_VALIDOS VALUES(4, 1, 'MINIMIZAR_ERROR_CUADRATICO');




/*Tabla de configuración de escenarios*/
DROP TABLE IA_APP.T_CONFIG_ESCENARIOS;
CREATE TABLE IA_APP.T_CONFIG_ESCENARIOS(ID_ESCENARIO INT          NOT NULL,
										ID_PARAM     INT          NOT NULL,
										VALOR        VARCHAR(100) NOT NULL,
										F_CONFIG     DATETIME     NOT NULL);
								
ALTER TABLE IA_APP.T_CONFIG_ESCENARIOS
	ADD CONSTRAINT PK_T_CONFIG_ESCENARIOS PRIMARY KEY(ID_ESCENARIO, ID_PARAM);
ALTER TABLE IA_APP.T_CONFIG_ESCENARIOS
	ADD CONSTRAINT FK_T_CONFIG_ESCENARIOS FOREIGN KEY(ID_ESCENARIO) REFERENCES IA_APP.T_ESCENARIOS(ID_ESCENARIO);				
ALTER TABLE IA_APP.T_CONFIG_ESCENARIOS
	ADD CONSTRAINT FK_T_CONFIG_ESCENARIOS_2 FOREIGN KEY(ID_PARAM) REFERENCES IA_APP.T_CONFIG_ESC_PARAM(ID_PARAM);						
CREATE INDEX IND_T_CONFIG_ESCENARIOS_1 ON IA_APP.T_CONFIG_ESCENARIOS (ID_ESCENARIO, ID_PARAM);



/*Tabla de autocorrelaciones*/
DROP TABLE IA_APP.T_ESCENARIOS_AUTOCORRELACION;
					
CREATE TABLE IA_APP.T_ESCENARIOS_AUTOCORRELACION(ID_ESCENARIO  INT           NOT NULL,
											     CAMPO         VARCHAR(100)  NOT NULL,
											     AUTOCORREL    INT           NOT NULL);

ALTER TABLE IA_APP.T_ESCENARIOS_AUTOCORREL
	ADD CONSTRAINT PK_T_ESCENARIOS_AUTOCORRELACION PRIMARY KEY (ID_ESCENARIO, CAMPO);

ALTER TABLE IA_APP.T_ESCENARIOS_AUTOCORREL
	ADD CONSTRAINT FK_T_ESCENARIOS_AUTOCORRELACION FOREIGN KEY(ID_ESCENARIO) REFERENCES IA_APP.T_ESCENARIOS(ID_ESCENARIO);	
					
/*Tabla de pesos*/
DROP TABLE IA_APP.T_PESOS;
CREATE TABLE IA_APP.T_PESOS(ID_PESO            INT             NOT NULL,
							ID_ESCENARIO       INT             NOT NULL,
							I_PESO             INT             NOT NULL,
							J_PESO             INT             NOT NULL,
							K_PESO             INT             NOT NULL,
							VALOR_PESO		   NUMERIC(21,18)  NOT NULL);

ALTER TABLE IA_APP.T_PESOS
	ADD CONSTRAINT PK_T_PESOS PRIMARY KEY (ID_PESO);
	
ALTER TABLE IA_APP.T_PESOS
	ADD CONSTRAINT FK_T_PESOS FOREIGN KEY(ID_ESCENARIO) REFERENCES IA_APP.T_ESCENARIOS(ID_ESCENARIO);	
		
ALTER TABLE IA_APP.T_PESOS
	ADD CONSTRAINT UK_T_PESOS UNIQUE KEY (ID_ESCENARIO, K_PESO, I_PESO, J_PESO);

CREATE INDEX IND_T_PESOS_1 ON IA_APP.T_PESOS(ID_ESCENARIO, K_PESO, I_PESO);

CREATE INDEX IND_T_PESOS_2 ON IA_APP.T_PESOS(ID_ESCENARIO, K_PESO);
 
	
	
	
	
	
	
	
	